# Generated by Django 4.2.5 on 2023-10-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_follow_app', '0003_hnuser_created_hnuser_notes_hnuser_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='hnuser',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hnuser',
            name='karma',
            field=models.IntegerField(null=True),
        ),
    ]
