# Generated by Django 4.2.5 on 2023-10-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_follow_app', '0004_hnuser_about_hnuser_karma'),
    ]

    operations = [
        migrations.CreateModel(
            name='HnSubmission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('type', models.CharField(max_length=16)),
                ('by', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
