# Generated by Django 4.2.5 on 2023-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_follow_app', '0005_hnsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnsubmission',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
