# Generated by Django 4.2.5 on 2023-10-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hn_follow_app", "0006_alter_hnsubmission_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hnsubmission",
            name="time",
            field=models.CharField(max_length=32),
        ),
    ]
