# Generated by Django 4.2.5 on 2023-10-08 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hn_follow_app", "0007_alter_hnsubmission_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="hnuser",
            name="user",
            field=models.ManyToManyField(
                related_name="hn_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="hnuser",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
